services:
  - type: web
    name: orion-platform
    env: node
    plan: free
    region: oregon
    rootDir: .
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: orion-env-variables
